In [34]:
import numpy as np
import sklearn
from sklearn import preprocessing
import pandas as pd

In [35]:
#data = pandas.read_csv('dataset_diabetes/diabetic_data.csv', ',')

In [36]:
df = pd.DataFrame.from_csv('dataset_diabetes/diabetic_data.csv')

In [37]:
df.head()

patient_nbr             race  gender      age weight  \
encounter_id                                                         
2278392           8222157        Caucasian  Female   [0-10)      ?   
149190           55629189        Caucasian  Female  [10-20)      ?   
64410            86047875  AfricanAmerican  Female  [20-30)      ?   
500364           82442376        Caucasian    Male  [30-40)      ?   
16680            42519267        Caucasian    Male  [40-50)      ?   

              admission_type_id  discharge_disposition_id  \
encounter_id                                                
2278392                       6                        25   
149190                        1                         1   
64410                         1                         1   
500364                        1                         1   
16680                         1                         1   

              admission_source_id  time_in_hospital payer_code    ...      \
encounter_id                                                      ...       
2278392                         1                 1          ?    ...       
149190                          7                 3          ?    ...       
64410                           7                 2          ?    ...       
500364                          7                 2          ?    ...       
16680                           7                 1          ?    ...       

             citoglipton  insulin  glyburide-metformin  glipizide-metformin  \
encounter_id                                                                  
2278392               No       No                   No                   No   
149190                No       Up                   No                   No   
64410                 No       No                   No                   No   
500364                No       Up                   No                   No   
16680                 No   Steady                   No                   No   

              glimepiride-pioglitazone  metformin-rosiglitazone  \
encounter_id                                                      
2278392                             No                       No   
149190                              No                       No   
64410                               No                       No   
500364                              No                       No   
16680                               No                       No   

              metformin-pioglitazone change diabetesMed readmitted  
encounter_id                                                        
2278392                           No     No          No         NO  
149190                            No     Ch         Yes        >30  
64410                             No     No         Yes         NO  
500364                            No     Ch         Yes         NO  
16680                             No     Ch         Yes         NO  

[5 rows x 49 columns]

# Preprocessing

In [38]:
df.readmitted.unique()

array(['NO', '>30', '<30'], dtype=object)

In [39]:
# transform readmitted categories into numerical values
#readmittedEncoder = preprocessing.LabelEncoder()
#readmittedEncoder.fit(df.readmitted)
#df.readmitted = readmittedEncoder.transform(df.readmitted)

In [40]:
df.gender.unique()

array(['Female', 'Male', 'Unknown/Invalid'], dtype=object)

In [41]:
# transform genders into numerical values (female = 0, male = 1, unknown = 2)
genderEncoder = preprocessing.LabelEncoder()
genderEncoder.fit(df.gender)
df.gender = genderEncoder.transform(df.gender)

In [42]:
df.age.unique()

array(['[0-10)', '[10-20)', '[20-30)', '[30-40)', '[40-50)', '[50-60)',
       '[60-70)', '[70-80)', '[80-90)', '[90-100)'], dtype=object)

In [43]:
# transforms range string into a numerical value in the middle of the range
def rangeStringToMiddle(rangeString):
    rangeString = rangeString[1:-1] #remove brackets
    rangeString = str.split(rangeString, '-')
    return (int(rangeString[0]) + int(rangeString[1])) / 2

In [44]:
rangeStringToMiddle('[70-80)')

75

In [45]:
# transform age range into one numerical value
df.age = df.age.apply(rangeStringToMiddle)

In [46]:
df.weight.unique()

array(['?', '[75-100)', '[50-75)', '[0-25)', '[100-125)', '[25-50)',
       '[125-150)', '[175-200)', '[150-175)', '>200'], dtype=object)

In [47]:
# transforms age range string into an age in the middle of the range
def weightRangeToWeight(weightRange):
    if weightRange == '?':
        return 0
    if weightRange == '>200':
        return 200
    return rangeStringToMiddle(weightRange)

In [48]:
# transform weight range into one numerical value
df.weight = df.weight.apply(weightRangeToWeight)

In [49]:
df.weight.unique()

array([  0,  87,  62,  12, 112,  37, 137, 187, 162, 200])

In [50]:
df.race.unique()

array(['Caucasian', 'AfricanAmerican', '?', 'Other', 'Asian', 'Hispanic'], dtype=object)

In [51]:
df.admission_type_id.unique()

array([6, 1, 2, 3, 4, 5, 8, 7])

In [52]:
df.admission_source_id.unique()

array([ 1,  7,  2,  4,  5,  6, 20,  3, 17,  8,  9, 14, 10, 22, 11, 25, 13])

In [53]:
df.payer_code.unique()

array(['?', 'MC', 'MD', 'HM', 'UN', 'BC', 'SP', 'CP', 'SI', 'DM', 'CM',
       'CH', 'PO', 'WC', 'OT', 'OG', 'MP', 'FR'], dtype=object)

In [54]:
df.discharge_disposition_id.unique()

array([25,  1,  3,  6,  2,  5, 11,  7, 10,  4, 14, 18,  8, 13, 12, 16, 17,
       22, 23,  9, 20, 15, 24, 28, 19, 27])

In [55]:
df.medical_specialty.unique()

array(['Pediatrics-Endocrinology', '?', 'InternalMedicine',
       'Family/GeneralPractice', 'Cardiology', 'Surgery-General',
       'Orthopedics', 'Gastroenterology',
       'Surgery-Cardiovascular/Thoracic', 'Nephrology',
       'Orthopedics-Reconstructive', 'Psychiatry', 'Emergency/Trauma',
       'Pulmonology', 'Surgery-Neuro',
       'Obsterics&Gynecology-GynecologicOnco', 'ObstetricsandGynecology',
       'Pediatrics', 'Hematology/Oncology', 'Otolaryngology',
       'Surgery-Colon&Rectal', 'Pediatrics-CriticalCare', 'Endocrinology',
       'Urology', 'Psychiatry-Child/Adolescent', 'Pediatrics-Pulmonology',
       'Neurology', 'Anesthesiology-Pediatric', 'Radiology',
       'Pediatrics-Hematology-Oncology', 'Psychology', 'Podiatry',
       'Gynecology', 'Oncology', 'Pediatrics-Neurology', 'Surgery-Plastic',
       'Surgery-Thoracic', 'Surgery-PlasticwithinHeadandNeck',
       'Ophthalmology', 'Surgery-Pediatric',
       'Pediatrics-EmergencyMedicine', 'PhysicalMedicineandRehabilit

In [56]:
categoricalColumns = ['readmitted', 'race', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'payer_code', 'medical_specialty']
for columnName in categoricalColumns:
    oneHotColumns = pd.get_dummies(df[columnName], prefix=(columnName + '_'), prefix_sep='')
    df = df.join(oneHotColumns)

In [57]:
df.head()

patient_nbr             race  gender  age  weight  \
encounter_id                                                      
2278392           8222157        Caucasian       0    5       0   
149190           55629189        Caucasian       0   15       0   
64410            86047875  AfricanAmerican       0   25       0   
500364           82442376        Caucasian       1   35       0   
16680            42519267        Caucasian       1   45       0   

              admission_type_id  discharge_disposition_id  \
encounter_id                                                
2278392                       6                        25   
149190                        1                         1   
64410                         1                         1   
500364                        1                         1   
16680                         1                         1   

              admission_source_id  time_in_hospital payer_code  \
encounter_id                                                     
2278392                         1                 1          ?   
149190                          7                 3          ?   
64410                           7                 2          ?   
500364                          7                 2          ?   
16680                           7                 1          ?   

                        ...            medical_specialty_Surgery-General  \
encounter_id            ...                                                
2278392                 ...                                            0   
149190                  ...                                            0   
64410                   ...                                            0   
500364                  ...                                            0   
16680                   ...                                            0   

              medical_specialty_Surgery-Maxillofacial  \
encounter_id                                            
2278392                                             0   
149190                                              0   
64410                                               0   
500364                                              0   
16680                                               0   

              medical_specialty_Surgery-Neuro  \
encounter_id                                    
2278392                                     0   
149190                                      0   
64410                                       0   
500364                                      0   
16680                                       0   

              medical_specialty_Surgery-Pediatric  \
encounter_id                                        
2278392                                         0   
149190                                          0   
64410                                           0   
500364                                          0   
16680                                           0   

              medical_specialty_Surgery-Plastic  \
encounter_id                                      
2278392                                       0   
149190                                        0   
64410                                         0   
500364                                        0   
16680                                         0   

              medical_specialty_Surgery-PlasticwithinHeadandNeck  \
encounter_id                                                       
2278392                                                       0    
149190                                                        0    
64410                                                         0    
500364                                                        0    
16680                                                         0    

              medical_specialty_Surgery-Thoracic  \
encounter_id                                       
2278392                                        0   
149190       

# Training

In [65]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

In [66]:
clf = OneVsRestClassifier(LinearDiscriminantAnalysis())

In [67]:
featureColumns = ['age', 'weight', 'gender']
labelColumns = ['readmitted_<30', 'readmitted_>30', 'readmitted_NO']
features = df[list(featureColumns)].values
labels = df[list(labelColumns)].values

In [68]:
clf.fit(features,labels)

OneVsRestClassifier(estimator=LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001),
          n_jobs=1)

In [69]:
cross_val_score(clf, features, labels, n_jobs=1)

array([ 0.54133011,  0.48528978,  0.55489063])